FREERTOS_SIM_FLAGS_COMMON := -D TGT_OS_TYPE_FREERTOS -pthread

FREERTOS_SIM_INCLUDES_COMMON := -I$(BUILD_ROOT)/Fw/Types/Linux -I$(BUILD_ROOT)/Os/FreeRTOS/FreeRTOS-Sim/Source/include -I$(BUILD_ROOT)/Os -I$(BUILD_ROOT)/Os/FreeRTOS -I$(BUILD_ROOT)/Os/FreeRTOS/FreeRTOS-Sim/Source/portable/GCC/POSIX
