include $(BUILD_ROOT)/mk/configs/compiler/linux_gnu_common.mk
include $(BUILD_ROOT)/mk/configs/compiler/include_common.mk
include $(BUILD_ROOT)/mk/configs/compiler/freertos_real_common.mk
include $(BUILD_ROOT)/mk/configs/compiler/ut_flags.mk

ifeq ("$(HOST)","Darwin")
CFLAGS :=   $(DEBUG) \
$(FREERTOS_SIM_GNU_CFLAGS) \
$(FREERTOS_SIM_GNU_INCLUDES) \
$(FREERTOS_SIM_FLAGS_COMMON) \
$(FREERTOS_SIM_INCLUDES_COMMON) \
$(COVERAGE) \
$(UT_FLAGS)

CXXFLAGS := $(DEBUG) \
$(FREERTOS_SIM_GNU_CXXFLAGS) \
$(FREERTOS_SIM_GNU_INCLUDES) \
$(FREERTOS_SIM_FLAGS_COMMON) \
$(FREERTOS_SIM_INCLUDES_COMMON) \
$(COVERAGE) \
$(UT_FLAGS) \
-fno-rtti

LINK_BIN_FLAGS := $(LINK_BIN_FLAGS) $(COVERAGE)
endif

ifeq ("$(HOST)","Linux")
CFLAGS :=   $(DEBUG) \
$(FREERTOS_SIM_GNU_CFLAGS) \
$(FREERTOS_SIM_GNU_INCLUDES) \
$(FREERTOS_SIM_FLAGS_COMMON) \
$(FREERTOS_SIM_INCLUDES_COMMON) \
$(COVERAGE) \
$(UT_FLAGS)

CXXFLAGS := $(DEBUG) \
$(FREERTOS_SIM_GNU_CXXFLAGS) \
$(FREERTOS_SIM_GNU_INCLUDES) \
$(FREERTOS_SIM_FLAGS_COMMON) \
$(FREERTOS_SIM_INCLUDES_COMMON) \
$(COVERAGE) \
$(UT_FLAGS)

LINK_BIN_FLAGS := $(LINK_BIN_FLAGS) $(COVERAGE)
endif

ifeq ("$(HOST)","FREERTOS_REAL")
CFLAGS :=   $(DEBUG) \
$(FREERTOS_REAL_GNU_CFLAGS) \
$(FREERTOS_REAL_GNU_INCLUDES) \
$(FREERTOS_REAL_FLAGS_COMMON) \
$(FREERTOS_REAL_INCLUDES_COMMON) \
$(COVERAGE) \
$(UT_FLAGS)

CXXFLAGS := $(DEBUG) \
$(FREERTOS_REAL_GNU_CXXFLAGS) \
$(FREERTOS_REAL_GNU_INCLUDES) \
$(FREERTOS_REAL_FLAGS_COMMON) \
$(FREERTOS_REAL_INCLUDES_COMMON) \
$(COVERAGE) \
$(UT_FLAGS)

LINK_BIN_FLAGS := $(LINK_BIN_FLAGS) $(COVERAGE)
endif

COMPILER := freertos-real-debug-gnu-ut
