LINUX_FLAGS_COMMON := -DTGT_OS_TYPE_LINUX

#LINUX_INCLUDES_COMMON := -I$(BUILD_ROOT)/Fw/Types/Linux
LINUX_INCLUDES_COMMON := -I$(BUILD_ROOT)/Fw/Types/Linux -I$(BUILD_ROOT)/Os/FreeRTOS/Source/include -I$(BUILD_ROOT)/Os -I$(BUILD_ROOT)/Os/FreeRTOS
